/**
 * @fileoverview gRPC-Web generated client stub for saas.noti.api.grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.15.8
// source: notification.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as notification_pb from './notification_pb';


export class UserDeviceServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSaveUserDevice = new grpcWeb.MethodDescriptor(
    '/saas.noti.api.grpc.UserDeviceService/SaveUserDevice',
    grpcWeb.MethodType.UNARY,
    notification_pb.UserDeviceRequest,
    notification_pb.UserDeviceResponse,
    (request: notification_pb.UserDeviceRequest) => {
      return request.serializeBinary();
    },
    notification_pb.UserDeviceResponse.deserializeBinary
  );

  saveUserDevice(
    request: notification_pb.UserDeviceRequest,
    metadata: grpcWeb.Metadata | null): Promise<notification_pb.UserDeviceResponse>;

  saveUserDevice(
    request: notification_pb.UserDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notification_pb.UserDeviceResponse) => void): grpcWeb.ClientReadableStream<notification_pb.UserDeviceResponse>;

  saveUserDevice(
    request: notification_pb.UserDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notification_pb.UserDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/saas.noti.api.grpc.UserDeviceService/SaveUserDevice',
        request,
        metadata || {},
        this.methodDescriptorSaveUserDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/saas.noti.api.grpc.UserDeviceService/SaveUserDevice',
    request,
    metadata || {},
    this.methodDescriptorSaveUserDevice);
  }

}

